// 快速工具库扩展脚本 - 生成100+新工具数据
// 用法: node scripts/expand-tools.js > new_tools.json

const newTools = [
    // ---- 论文写作增强 (75-80) ----
    {id: 75, name: "Quillbot", category: "writing", desc: "AI 改写工具，支持论文语句优化、学术表达提升、避免抄袭检查，支持多种学术写作风格。", logo: "https://www.google.com/s2/favicons?domain=quillbot.com&sz=64", icon: "fas fa-edit", color: "#0066cc", tags: ["改写", "降重"], pricing: "freemium", region: "foreign", rating: 4.4, users: "500万+", url: "https://quillbot.com"},
    {id: 76, name: "DeepL Write", category: "writing", desc: "DeepL 推出的学术写作增强工具，提供语法改正、措辞建议和流畅性优化，支持多语言学术写作。", logo: "https://www.google.com/s2/favicons?domain=deepl.com&sz=64", icon: "fas fa-language", color: "#002e7d", tags: ["翻译", "润色"], pricing: "freemium", region: "foreign", rating: 4.6, users: "300万+", url: "https://www.deepl.com/write", isNew: true},
    {id: 77, name: "Grammarly", category: "writing", desc: "全球最受欢迎的语法检查工具，支持学术写作模式，提供实时拼写、语法、标点和风格建议。", logo: "https://www.google.com/s2/favicons?domain=grammarly.com&sz=64", icon: "fas fa-check", color: "#15c39a", tags: ["语法检查", "写作助手"], pricing: "freemium", region: "foreign", rating: 4.7, users: "1000万+", url: "https://www.grammarly.com"},
    {id: 78, name: "Turnitin", category: "writing", desc: "学术查重和论文提交系统，识别引用不当和可能的抄袭，被全球高校广泛采用。", logo: "https://www.google.com/s2/favicons?domain=turnitin.com&sz=64", icon: "fas fa-shield-alt", color: "#cc0000", tags: ["查重", "反抄袭"], pricing: "paid", region: "foreign", rating: 4.5, users: "200万+", url: "https://www.turnitin.com"},
    {id: 79, name: "Copyscape", category: "writing", desc: "强大的抄袭检测工具，扫描互联网中的重复内容，确保论文原创性。", logo: "https://www.google.com/s2/favicons?domain=copyscape.com&sz=64", icon: "fas fa-copy", color: "#4267b2", tags: ["查重", "原创性"], pricing: "freemium", region: "foreign", rating: 4.3, users: "50万+", url: "https://www.copyscape.com"},
    {id: 80, name: "Wordtune", category: "writing", desc: "AI 驱动的句式改写工具，一键优化学术表达，支持保留原意基础上提升专业性。", logo: "https://www.google.com/s2/favicons?domain=wordtune.com&sz=64", icon: "fas fa-wand-magic-sparkles", color: "#6c5ce7", tags: ["改写", "AI写作"], pricing: "freemium", region: "foreign", rating: 4.5, users: "100万+", url: "https://www.wordtune.com"},

    // ---- 文献阅读增强 (81-85) ----
    {id: 81, name: "Semantic Scholar", category: "reading", desc: "AI 驱动的学术搜索引擎，从海量论文中推荐相关工作，支持引用智能排序和影响力分析。", logo: "https://www.google.com/s2/favicons?domain=semanticscholar.org&sz=64", icon: "fas fa-brain", color: "#4c6ef5", tags: ["文献检索", "引用分析"], pricing: "free", region: "foreign", rating: 4.6, users: "500万+", url: "https://www.semanticscholar.org"},
    {id: 82, name: "Zotero", category: "reading", desc: "开源文献管理工具，支持自动标签、全文搜索、团队协作，深度集成 Word 和 Google Docs。", logo: "https://www.google.com/s2/favicons?domain=zotero.org&sz=64", icon: "fas fa-folder-open", color: "#cc2927", tags: ["文献管理", "开源"], pricing: "free", region: "foreign", rating: 4.7, users: "200万+", url: "https://www.zotero.org"},
    {id: 83, name: "Mendeley", category: "reading", desc: "Elsevier 旗下文献管理平台，支持 PDF 标注、合作阅读、云端同步和发现相关论文推荐。", logo: "https://www.google.com/s2/favicons?domain=mendeley.com&sz=64", icon: "fas fa-book-bookmark", color: "#b71c1c", tags: ["文献管理", "云端同步"], pricing: "freemium", region: "foreign", rating: 4.5, users: "300万+", url: "https://www.mendeley.com"},
    {id: 84, name: "Notion AI", category: "reading", desc: "Notion 内置 AI，支持在笔记中提问、总结论文要点、自动分类整理阅读记录。", logo: "https://www.google.com/s2/favicons?domain=notion.so&sz=64", icon: "fas fa-lightbulb", color: "#000000", tags: ["笔记管理", "AI助手"], pricing: "freemium", region: "foreign", rating: 4.5, users: "500万+", url: "https://www.notion.so"},
    {id: 85, name: "PubMed", category: "reading", desc: "NIH 维护的生物医学文献免费数据库，包含 3000+ 万条记录，支持高级搜索和 AI 引导检索。", logo: "https://www.google.com/s2/favicons?domain=pubmed.ncbi.nlm.nih.gov&sz=64", icon: "fas fa-flask", color: "#0072b5", tags: ["文献检索", "生物医学"], pricing: "free", region: "foreign", rating: 4.6, users: "1000万+", url: "https://pubmed.ncbi.nlm.nih.gov"},

    // ---- 数据分析工具增强 (86-95) ----
    {id: 86, name: "Google Colab", category: "data", desc: "免费云端 Jupyter 环境，提供 GPU/TPU 加速，集成 GitHub 导入和 Google Drive 联动，无需本地配置。", logo: "https://www.google.com/s2/favicons?domain=colab.research.google.com&sz=64", icon: "fab fa-google", color: "#4285f4", tags: ["数据分析", "云计算"], pricing: "free", region: "foreign", rating: 4.7, users: "500万+", url: "https://colab.research.google.com", hot: true},
    {id: 87, name: "Kaggle", category: "data", desc: "数据科学竞赛平台，汇聚数据集、笔记本和讨论，支持协作竞赛和技能展示。", logo: "https://www.google.com/s2/favicons?domain=kaggle.com&sz=64", icon: "fas fa-chart-bar", color: "#20beff", tags: ["数据竞赛", "数据集"], pricing: "free", region: "foreign", rating: 4.5, users: "300万+", url: "https://www.kaggle.com"},
    {id: 88, name: "Plotly", category: "data", desc: "交互式可视化库，支持 Python/R/JavaScript，生成出版级质量的图表和仪表板。", logo: "https://www.google.com/s2/favicons?domain=plotly.com&sz=64", icon: "fas fa-chart-line", color: "#003fff", tags: ["数据可视化", "交互图表"], pricing: "freemium", region: "foreign", rating: 4.6, users: "200万+", url: "https://plotly.com"},
    {id: 89, name: "Tableau", category: "data", desc: "企业级 BI 工具，支持自助式数据分析和交互式仪表板，无需编程即可生成专业图表。", logo: "https://www.google.com/s2/favicons?domain=tableau.com&sz=64", icon: "fas fa-chart-pie", color: "#ffb81c", tags: ["BI分析", "数据可视化"], pricing: "paid", region: "foreign", rating: 4.6, users: "100万+", url: "https://www.tableau.com"},
    {id: 90, name: "Power BI", category: "data", desc: "微软 BI 解决方案，与 Excel 无缝集成，支持实时数据刷新和协作报告共享。", logo: "https://www.google.com/s2/favicons?domain=powerbi.microsoft.com&sz=64", icon: "fab fa-microsoft", color: "#f25022", tags: ["BI分析", "Excel集成"], pricing: "paid", region: "foreign", rating: 4.5, users: "150万+", url: "https://powerbi.microsoft.com"},
    {id: 91, name: "Apache Spark", category: "data", desc: "大数据分析框架，支持分布式计算和机器学习，性能远超 Hadoop MapReduce。", logo: "https://www.google.com/s2/favicons?domain=spark.apache.org&sz=64", icon: "fas fa-fire", color: "#e35a31", tags: ["大数据", "分布式"], pricing: "free", region: "foreign", rating: 4.6, users: "50万+", url: "https://spark.apache.org"},
    {id: 92, name: "Pandas Profiling", category: "data", desc: "一行代码生成 EDA 报告，自动分析缺失值、相关性和离群点，提供交互式 HTML 报告。", logo: "https://www.google.com/s2/favicons?domain=pandas-profiling.ydata.ai&sz=64", icon: "fas fa-magnifying-glass", color: "#150458", tags: ["数据探索", "EDA"], pricing: "free", region: "foreign", rating: 4.5, users: "100万+", url: "https://pandas-profiling.ydata.ai"},
    {id: 93, name: "Apache Superset", category: "data", desc: "开源数据可视化和 BI 工具，支持多数据库连接和实时刷新，可视化操作无需代码。", logo: "https://www.google.com/s2/favicons?domain=superset.apache.org&sz=64", icon: "fas fa-database", color: "#20a0b0", tags: ["BI分析", "开源"], pricing: "free", region: "foreign", rating: 4.4, users: "50万+", url: "https://superset.apache.org"},
    {id: 94, name: "Metabase", category: "data", desc: "简单易用的开源 BI 工具，一分钟连接数据库并创建仪表板，零代码查询。", logo: "https://www.google.com/s2/favicons?domain=metabase.com&sz=64", icon: "fas fa-chart-pie", color: "#509ee3", tags: ["BI分析", "开源"], pricing: "freemium", region: "foreign", rating: 4.5, users: "100万+", url: "https://www.metabase.com"},
    {id: 95, name: "Orange Data Mining", category: "data", desc: "可视化数据挖掘工具，拖拽式工作流，支持机器学习和统计分析，免费开源。", logo: "https://www.google.com/s2/favicons?domain=orange.readthedocs.io&sz=64", icon: "fas fa-apple", color: "#ff8c00", tags: ["数据挖掘", "可视化"], pricing: "free", region: "foreign", rating: 4.4, users: "30万+", url: "https://orange.readthedocs.io"},

    // ---- 科研绘图增强 (96-105) ----
    {id: 96, name: "Matplotlib", category: "figure", desc: "Python 绘图库，生成出版级质量静态图表，是数据可视化的基础工具。", logo: "https://www.google.com/s2/favicons?domain=matplotlib.org&sz=64", icon: "fas fa-chart-area", color: "#1f77b4", tags: ["Python绘图", "开源"], pricing: "free", region: "foreign", rating: 4.5, users: "200万+", url: "https://matplotlib.org"},
    {id: 97, name: "Seaborn", category: "figure", desc: "基于 Matplotlib 的高级绘图库，提供统计图表模板和配色方案，与 Pandas 深度集成。", logo: "https://www.google.com/s2/favicons?domain=seaborn.pydata.org&sz=64", icon: "fas fa-palette", color: "#13adc7", tags: ["Python绘图", "统计图"], pricing: "free", region: "foreign", rating: 4.6, users: "150万+", url: "https://seaborn.pydata.org"},
    {id: 98, name: "Graphviz", category: "figure", desc: "图表可视化工具，支持流程图、组织结构图、网络拓扑等，广泛用于科研文档。", logo: "https://www.google.com/s2/favicons?domain=graphviz.org&sz=64", icon: "fas fa-diagram-project", color: "#244c5a", tags: ["图表绘制", "开源"], pricing: "free", region: "foreign", rating: 4.4, users: "50万+", url: "https://graphviz.org"},
    {id: 99, name: "Inkscape", category: "figure", desc: "开源矢量图编辑器，用于创建和编辑矢量图形、流程图和科学插图。", logo: "https://www.google.com/s2/favicons?domain=inkscape.org&sz=64", icon: "fas fa-pen-fancy", color: "#000000", tags: ["矢量图", "开源"], pricing: "free", region: "foreign", rating: 4.4, users: "100万+", url: "https://inkscape.org"},
    {id: 100, name: "OmniGraffle", category: "figure", desc: "专业图表设计工具，支持流程图、线框图和思维导图，Mac 端最佳绘图软件。", logo: "https://www.google.com/s2/favicons?domain=omnigraffle.com&sz=64", icon: "fas fa-shapes", color: "#2a4078", tags: ["专业绘图", "思维导图"], pricing: "paid", region: "foreign", rating: 4.6, users: "30万+", url: "https://www.omnigraffle.com"},
    {id: 101, name: "Adobe Illustrator", category: "figure", desc: "行业标准矢量图设计工具，功能强大，用于创建科学插图和专业图形。", logo: "https://www.google.com/s2/favicons?domain=adobe.com&sz=64", icon: "fab fa-adobe", color: "#ff0000", tags: ["专业设计", "付费"], pricing: "paid", region: "foreign", rating: 4.7, users: "500万+", url: "https://www.adobe.com/products/illustrator"},
    {id: 102, name: "ImageMagick", category: "figure", desc: "命令行图像处理工具，支持格式转换、特效处理和批处理，脚本友好。", logo: "https://www.google.com/s2/favicons?domain=imagemagick.org&sz=64", icon: "fas fa-image", color: "#52b3d9", tags: ["图像处理", "开源"], pricing: "free", region: "foreign", rating: 4.5, users: "50万+", url: "https://imagemagick.org"},
    {id: 103, name: "Canva", category: "figure", desc: "在线设计工具，提供海量模板和素材，支持快速设计海报、信息图和学术演示。", logo: "https://www.google.com/s2/favicons?domain=canva.com&sz=64", icon: "fas fa-magic", color: "#00c4cc", tags: ["在线设计", "模板"], pricing: "freemium", region: "foreign", rating: 4.5, users: "1000万+", url: "https://www.canva.com"},
    {id: 104, name: "Figma", category: "figure", desc: "云端协作设计工具，支持实时协作、原型设计和设计系统管理，越来越多科研小组采用。", logo: "https://www.google.com/s2/favicons?domain=figma.com&sz=64", icon: "fas fa-pen-tool", color: "#2c3e50", tags: ["设计工具", "协作"], pricing: "freemium", region: "foreign", rating: 4.6, users: "300万+", url: "https://www.figma.com"},
    {id: 105, name: "Miro", category: "figure", desc: "在线白板工具，支持思维导图、流程图、故事板等，适合团队头脑风暴和项目规划。", logo: "https://www.google.com/s2/favicons?domain=miro.com&sz=64", icon: "fas fa-sticky-note", color: "#ffd700", tags: ["白板", "协作"], pricing: "freemium", region: "foreign", rating: 4.5, users: "200万+", url: "https://www.miro.com"},

    // ---- 代码助手增强 (106-120) ----
    {id: 106, name: "GitHub Copilot", category: "code", desc: "AI 代码补全工具，由 OpenAI Codex 驱动，支持 VS Code、Vim 等编辑器，大幅提高编码效率。", logo: "https://www.google.com/s2/favicons?domain=github.com&sz=64", icon: "fab fa-github", color: "#333", tags: ["代码补全", "GitHub"], pricing: "paid", region: "foreign", rating: 4.7, users: "100万+", url: "https://github.com/features/copilot", hot: true},
    {id: 107, name: "CodeBERT", category: "code", desc: "微软开源的代码理解模型，支持代码搜索、克隆检测和代码标签预测。", logo: "https://www.google.com/s2/favicons?domain=microsoft.com&sz=64", icon: "fab fa-microsoft", color: "#0078d4", tags: ["代码分析", "开源"], pricing: "free", region: "foreign", rating: 4.5, users: "20万+", url: "https://github.com/microsoft/CodeBERT"},
    {id: 108, name: "Tabnine", category: "code", desc: "AI 代码补全工具，支持多种编程语言和编辑器，可离线使用专业版。", logo: "https://www.google.com/s2/favicons?domain=tabnine.com&sz=64", icon: "fas fa-code", color: "#1976d2", tags: ["代码补全", "多语言"], pricing: "freemium", region: "foreign", rating: 4.4, users: "50万+", url: "https://www.tabnine.com"},
    {id: 109, name: "Codeium", category: "code", desc: "免费 AI 代码补全工具，不逊于付费工具，支持 70+ 编程语言和 40+ 编辑器。", logo: "https://www.google.com/s2/favicons?domain=codeium.com&sz=64", icon: "fas fa-laptop-code", color: "#06b6d4", tags: ["代码补全", "免费"], pricing: "freemium", region: "foreign", rating: 4.5, users: "100万+", url: "https://codeium.com"},
    {id: 110, name: "Copilot Chat", category: "code", desc: "GitHub Copilot 的对话式编码助手，实时代码解释、生成和修复建议。", logo: "https://www.google.com/s2/favicons?domain=github.com&sz=64", icon: "fab fa-github", color: "#333", tags: ["代码助手", "对话"], pricing: "paid", region: "foreign", rating: 4.6, users: "50万+", url: "https://github.com/features/copilot"},
    {id: 111, name: "AWS CodeWhisperer", category: "code", desc: "亚马逊推出的 AI 代码生成器，免费个人使用，支持 15+ 编程语言。", logo: "https://www.google.com/s2/favicons?domain=aws.amazon.com&sz=64", icon: "fab fa-aws", color: "#ff9900", tags: ["代码补全", "云服务"], pricing: "freemium", region: "foreign", rating: 4.4, users: "30万+", url: "https://aws.amazon.com/codewhisperer/", isNew: true},
    {id: 112, name: "StackBlitz", category: "code", desc: "在线 IDE，支持 Node.js、Angular、React 等，无需本地安装即可开发和分享代码。", logo: "https://www.google.com/s2/favicons?domain=stackblitz.com&sz=64", icon: "fas fa-bolt", color: "#00c0ff", tags: ["在线IDE", "Web开发"], pricing: "freemium", region: "foreign", rating: 4.5, users: "50万+", url: "https://stackblitz.com"},
    {id: 113, name: "Repl.it", category: "code", desc: "在线编程环境，支持 50+ 编程语言，适合学习和快速原型开发。", logo: "https://www.google.com/s2/favicons?domain=replit.com&sz=64", icon: "fas fa-terminal", color: "#ff0000", tags: ["在线IDE", "学习平台"], pricing: "freemium", region: "foreign", rating: 4.4, users: "100万+", url: "https://replit.com"},
    {id: 114, name: "Visual Studio Code", category: "code", desc: "微软开源代码编辑器，轻量级但功能强大，支持众多扩展，是研究人员的首选。", logo: "https://www.google.com/s2/favicons?domain=code.visualstudio.com&sz=64", icon: "fas fa-code", color: "#0078d4", tags: ["编辑器", "开源"], pricing: "free", region: "foreign", rating: 4.8, users: "500万+", url: "https://code.visualstudio.com"},
    {id: 115, name: "JetBrains IDEs", category: "code", desc: "专业集成开发环境，包括 PyCharm、IntelliJ 等，提供强大的代码分析和重构工具。", logo: "https://www.google.com/s2/favicons?domain=jetbrains.com&sz=64", icon: "fas fa-hammer", color: "#21d4fd", tags: ["IDE", "专业开发"], pricing: "paid", region: "foreign", rating: 4.7, users: "200万+", url: "https://www.jetbrains.com"},
    {id: 116, name: "Vim", category: "code", desc: "高效文本编辑器，学习曲线陡但生产力高，被全球开发者广泛使用。", logo: "https://www.google.com/s2/favicons?domain=vim.org&sz=64", icon: "fas fa-edit", color: "#019833", tags: ["编辑器", "开源"], pricing: "free", region: "foreign", rating: 4.6, users: "200万+", url: "https://www.vim.org"},
    {id: 117, name: "Neovim", category: "code", desc: "Vim 的现代化分支，改进了可扩展性和用户体验，支持 Lua 脚本和异步处理。", logo: "https://www.google.com/s2/favicons?domain=neovim.io&sz=64", icon: "fas fa-terminal", color: "#57a143", tags: ["编辑器", "开源"], pricing: "free", region: "foreign", rating: 4.5, users: "50万+", url: "https://neovim.io"},
    {id: 118, name: "GitKraken", category: "code", desc: "可视化 Git 客户端，简化版本控制操作，支持 GitHub、GitLab、Bitbucket。", logo: "https://www.google.com/s2/favicons?domain=gitkraken.com&sz=64", icon: "fas fa-code-branch", color: "#179287", tags: ["版本控制", "Git"], pricing: "freemium", region: "foreign", rating: 4.6, users: "100万+", url: "https://www.gitkraken.com"},
    {id: 119, name: "GitPod", category: "code", desc: "云端开发环境，一键启动预配置的开发容器，无需本地配置即可编码。", logo: "https://www.google.com/s2/favicons?domain=gitpod.io&sz=64", icon: "fas fa-cloud", color: "#ffb45b", tags: ["云IDE", "DevOps"], pricing: "freemium", region: "foreign", rating: 4.5, users: "50万+", url: "https://www.gitpod.io"},
    {id: 120, name: "Docker", category: "code", desc: "容器化技术，打包应用环境确保跨机器一致性，是现代科研计算的基础。", logo: "https://www.google.com/s2/favicons?domain=docker.com&sz=64", icon: "fab fa-docker", color: "#2496ed", tags: ["容器化", "DevOps"], pricing: "freemium", region: "foreign", rating: 4.7, users: "300万+", url: "https://www.docker.com"},

    // ---- 大语言模型增强 (121-140) ----
    {id: 121, name: "GPT-4", category: "llm", desc: "OpenAI 最强大模型，支持图像输入和 128K 上下文，推理能力业界领先。", logo: "https://www.google.com/s2/favicons?domain=openai.com&sz=64", icon: "fas fa-wand-magic-sparkles", color: "#10a37f", tags: ["大模型", "多模态"], pricing: "paid", region: "foreign", rating: 4.9, users: "100万+", url: "https://openai.com", hot: true},
    {id: 122, name: "Gemini Pro", category: "llm", desc: "Google 推出的多模态大模型，免费使用，在推理和编码方面表现出色。", logo: "https://www.google.com/s2/favicons?domain=gemini.google.com&sz=64", icon: "fab fa-google", color: "#4285f4", tags: ["大模型", "多模态"], pricing: "freemium", region: "foreign", rating: 4.7, users: "500万+", url: "https://gemini.google.com", hot: true},
    {id: 123, name: "Llama 2", category: "llm", desc: "Meta 开源大模型，可本地部署，性能接近 ChatGPT，社区活跃。", logo: "https://www.google.com/s2/favicons?domain=meta.com&sz=64", icon: "fas fa-code", color: "#0084ff", tags: ["开源模型", "本地部署"], pricing: "free", region: "foreign", rating: 4.5, users: "200万+", url: "https://github.com/facebookresearch/llama"},
    {id: 124, name: "Mistral 7B", category: "llm", desc: "高效开源模型，性能超 Llama 2，资源占用少，适合边缘计算场景。", logo: "https://www.google.com/s2/favicons?domain=mistral.ai&sz=64", icon: "fas fa-rocket", color: "#ff6b6b", tags: ["开源模型", "高效"], pricing: "free", region: "foreign", rating: 4.6, users: "100万+", url: "https://mistral.ai"},
    {id: 125, name: "Bing Chat", category: "llm", desc: "微软整合 ChatGPT 的搜索引擎，提供实时网络信息和源引用，免费使用。", logo: "https://www.google.com/s2/favicons?domain=bing.com&sz=64", icon: "fab fa-windows", color: "#0078d4", tags: ["搜索+AI", "实时信息"], pricing: "free", region: "foreign", rating: 4.5, users: "1000万+", url: "https://www.bing.com/chat"},
    {id: 126, name: "Perplexity AI", category: "llm", desc: "AI 搜索引擎，整合网络实时信息，提供带源引用的答案，适合学术信息查询。", logo: "https://www.google.com/s2/favicons?domain=perplexity.ai&sz=64", icon: "fas fa-magnifying-glass", color: "#00d4ff", tags: ["AI搜索", "学术"], pricing: "freemium", region: "foreign", rating: 4.6, users: "500万+", url: "https://www.perplexity.ai", hot: true},
    {id: 127, name: "PyTorch", category: "llm", desc: "深度学习框架，动态计算图设计，支持分布式训练，学术研究首选。", logo: "https://www.google.com/s2/favicons?domain=pytorch.org&sz=64", icon: "fas fa-brain", color: "#ee4c2c", tags: ["深度学习", "开源"], pricing: "free", region: "foreign", rating: 4.7, users: "300万+", url: "https://pytorch.org"},
    {id: 128, name: "TensorFlow", category: "llm", desc: "Google 开源深度学习框架，功能完整，支持从研究到生产的全流程。", logo: "https://www.google.com/s2/favicons?domain=tensorflow.org&sz=64", icon: "fab fa-google", color: "#ff6f00", tags: ["深度学习", "开源"], pricing: "free", region: "foreign", rating: 4.6, users: "200万+", url: "https://www.tensorflow.org"},
    {id: 129, name: "Hugging Face", category: "llm", desc: "AI 模型库和社区，汇聚数千个预训练模型，是 NLP 研究的中心。", logo: "https://www.google.com/s2/favicons?domain=huggingface.co&sz=64", icon: "fas fa-faces-smile", color: "#000000", tags: ["模型库", "社区"], pricing: "freemium", region: "foreign", rating: 4.8, users: "500万+", url: "https://huggingface.co", hot: true},
    {id: 130, name: "Replicate", category: "llm", desc: "无服务器 AI 模型部署平台，支持 API 调用数千个开源模型，按使用次数计费。", logo: "https://www.google.com/s2/favicons?domain=replicate.com&sz=64", icon: "fas fa-cloud", color: "#ffffff", tags: ["模型部署", "API"], pricing: "paid", region: "foreign", rating: 4.5, users: "50万+", url: "https://replicate.com", isNew: true},
    {id: 131, name: "Ollama", category: "llm", desc: "本地运行大模型的工具，支持 Llama 2、Mistral 等，简化离线部署流程。", logo: "https://www.google.com/s2/favicons?domain=ollama.ai&sz=64", icon: "fas fa-server", color: "#ffffff", tags: ["本地部署", "离线"], pricing: "free", region: "foreign", rating: 4.5, users: "50万+", url: "https://ollama.ai", isNew: true},
    {id: 132, name: "LangChain", category: "llm", desc: "大模型应用开发框架，简化 LLM 链式调用、记忆管理和工具集成。", logo: "https://www.google.com/s2/favicons?domain=langchain.com&sz=64", icon: "fas fa-link", color: "#1c3144", tags: ["框架", "LLM应用"], pricing: "free", region: "foreign", rating: 4.6, users: "100万+", url: "https://www.langchain.com"},
    {id: 133, name: "DeepSeek", category: "llm", desc: "国产顶尖大模型，代码推理能力超 GPT-4o，支持免费 API 调用。", logo: "https://www.google.com/s2/favicons?domain=deepseek.com&sz=64", icon: "fas fa-robot", color: "#0055ff", tags: ["国产模型", "代码推理"], pricing: "free", region: "domestic", rating: 4.7, users: "100万+", url: "https://chat.deepseek.com", hot: true},
    {id: 134, name: "通义千问", category: "llm", desc: "阿里开源大模型，支持长文本理解，可本地部署。", logo: "https://www.google.com/s2/favicons?domain=tongyi.aliyun.com&sz=64", icon: "fas fa-adn", color: "#ff6600", tags: ["国产模型", "开源"], pricing: "free", region: "domestic", rating: 4.5, users: "200万+", url: "https://tongyi.aliyun.com"},
    {id: 135, name: "文心一言", category: "llm", desc: "百度大模型，支持文本和图像理解，在搜索增强方面优势明显。", logo: "https://www.google.com/s2/favicons?domain=yiyan.baidu.com&sz=64", icon: "fab fa-baidu", color: "#2932e1", tags: ["国产模型", "搜索增强"], pricing: "free", region: "domestic", rating: 4.4, users: "300万+", url: "https://yiyan.baidu.com"},
];

// 导出为 JSON 便于插入到 js/data.js
console.log(JSON.stringify(newTools, null, 2));
